apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: reboot-agent
spec:
  selector:
    matchLabels:
      name: hoserface
  template:
    metadata:
      labels:
        name: hoserface
    spec:
      containers:
      - name: reboot-agent
        image: monopole/reboot-agent:latest
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
