apiVersion: apps/v1
kind: Deployment
metadata:
  name: reboot-controller
spec:
  selector:
    matchLabels:
      name: pumpkinjack
  replicas: 1
  template:
    metadata:
      labels:
        name: pumpkinjack
    spec:
      serviceAccountName: blah-reboot-account
      containers:
      - name: reboot-controller
        image: monopole/reboot-controller:ee360f28015ff85d3f57c86baf53a9bc03e1b805
