apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: reboot-agent
spec:
  selector:
    matchLabels:
      name: hoserface
  template:
    metadata:
      labels:
        name: hoserface
    spec:
      containers:
      - name: reboot-agent
        image: monopole/demo-reboot-agent:896e295637facb2fb213003cd6d3c14960c2e7cc
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
