apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: reboot-agent
spec:
  selector:
    matchLabels:
      name: hoserface
  template:
    metadata:
      labels:
        name: hoserface
    spec:
      containers:
      - name: reboot-agent
        image: monopole/demo-reboot-agent:0b75fdf4cbf09c70e5cefc8d1cbd872beefb70d5
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
