apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: reboot-agent
spec:
  selector:
    matchLabels:
      name: hoserface
  template:
    metadata:
      labels:
        name: hoserface
    spec:
      serviceAccountName: blah-reboot-account
      containers:
      - name: reboot-agent
        image: monopole/reboot-agent:ee360f28015ff85d3f57c86baf53a9bc03e1b805
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
