apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reboot-controller
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: reboot-controller
        image: monopole/demo-reboot-controller:0b75fdf4cbf09c70e5cefc8d1cbd872beefb70d5
