apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: reboot-agent
spec:
  selector:
    matchLabels:
      name: hoserface
  template:
    metadata:
      labels:
        name: hoserface
    spec:
      serviceAccountName: blah-reboot-account
      containers:
      - name: reboot-agent
        image: monopole/reboot-agent:d2f18115cef0ff5448edac607d25a67af96e1f61
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
